apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volumeclaim
spec:
  storageClassName: cloud-ssd-mongo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd-mongo
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
