apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  selector:
    matchLabels:
      app: products
  replicas: 2
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: tobiasbecode/sfshop-products
        ports:
          - containerPort: 8755
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  ports:
    - name: products
      port: 8755
      nodePort: 30893
  selector:
    app: products
  type: NodePort
