apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
  labels:
    app: rating
spec:
  selector:
    matchLabels:
      app: rating
  replicas: 2
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: tobiasbecode/sfshop-rating
        ports:
          - containerPort: 8751
---
apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  ports:
    - name: rating
      port: 8751
      nodePort: 30862
  selector:
    app: rating
  type: NodePort
