apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  ports:
    - name: rating
      port: 8751
  selector:
    app: rating
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  ports:
    - name: products
      port: 8755
  selector:
    app: products
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  ports:
    - name: order
      port: 8000
  selector:
    app: order
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2
spec:
  ports:
    - name: oauth2
      port: 8283
  selector:
    app: oauth2
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-naming-server
spec:
  ports:
    - name: eureka-naming-server
      port: 8761
  selector:
    app: eureka-naming-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  ports:
    - name: api-gateway
      port: 8765
  selector:
    app: api-gateway
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
