apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2
  labels:
    app: oauth2
spec:
  selector:
    matchLabels:
      app: oauth2
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
      - name: oauth2
        image: tobiasbecode/sfshop-oauth2
        ports:
          - containerPort: 8283
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2
spec:
  ports:
    - name: oauth2
      port: 8283
      nodePort: 30828
  selector:
    app: oauth2
  type: NodePort
